name: Build NixOS Configurations

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      # Don't cancel all jobs if one fails
      fail-fast: false
      matrix:
        include:
          - host: pluto
            runs-on: ubuntu-latest
          - host: juno
            runs-on: ubuntu-latest
          - host: flore
            runs-on: ubuntu-latest
          - host: charon
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          cachix_name: ${{ secrets.CACHIX_NAME }}
          cachix_authToken: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Build NixOS configuration for ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

  tests:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: pluto
            runs-on: ubuntu-latest
            check: pluto-boot
            system: x86_64-linux
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          cachix_name: ${{ secrets.CACHIX_NAME }}
          cachix_authToken: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Run ${{ matrix.host }} boot test
        run: nix build -L .#checks.${{ matrix.system }}.${{ matrix.check }}
