name: Charon

on:
  pull_request:
    branches:
      - main

jobs:
  Ci:
    uses: ./.github/workflows/_ci.yml
    with:
      host: charon
      check: charon-boot
      system: aarch64-linux
      runs-on: ubuntu-24.04-arm
    secrets:
      CACHIX_NAME: ${{ secrets.CACHIX_NAME }}
      CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
