name: Flore

on:
  pull_request:
    branches:
      - main

jobs:
  CI:
    uses: ./.github/workflows/ci.yml
    with:
      host: flore
      check: flore-boot
      system: x86_64-linux
      runs-on: ubuntu-latest
    secrets:
      CACHIX_NAME: ${{ secrets.CACHIX_NAME }}
      CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
